apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: \{{ template "fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: \{{ template "fullname" . }}
  minReplicas: \{{ .Values.replicaCount }}
  maxReplicas: \{{ .Values.maxReplicaCount }}
  targetCPUUtilizationPercentage: 60
